sudo: required

language: java
jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker --version