PUT http://{{host}}:{{port}}/roles/6
Content-Type: application/json

{
  "code": "T96",
  "name": "This is a test role",
  "description": "Change Description"
}

###
DELETE http://{{host}}:{{port}}/roles?code=TET
Accept: application/json

###
DELETE http://{{host}}:{{port}}/roles/6

###
POST http://{{host}}:{{port}}/roles
Content-Type: application/json

{
  "code": "XXX",
  "name": "guest",
  "description": "XXX Test insertion"
}

###
GET http://{{host}}:{{port}}/roles/1
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}

###
GET http://{{host}}:{{port}}/roles
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}

###
GET http://{{host}}:{{port}}/actuator
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}

###
GET http://{{host}}:{{port}}/greeting?guestName=worasit
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}

###
GET http://{{host}}:{{port}}/swagger
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}

###
GET http://{{host}}:{{port}}/api-docs
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}