POST http://{{host}}:{{port}}/roles
Content-Type: application/json

{
  "code": "TET",
  "name": "guest",
  "description": "",
  "updatedAt": null,
  "createdAt": "2020-09-27T15:56:29.682+0000"
}

###
GET http://{{host}}:{{port}}/roles/1
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}

###
GET http://{{host}}:{{port}}/roles
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}

###
GET http://{{host}}:{{port}}/actuator
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}

###
GET http://{{host}}:{{port}}/greeting?guestName=worasit
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}

###
GET http://{{host}}:{{port}}/swagger
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}

###
GET http://{{host}}:{{port}}/api-docs
Accept: application/json

> {% client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
}); %}