GET http://localhost:8080/actuator
Accept: application/json

###
GET http://localhost:8080/greeting?guestName=worasit
Accept: application/json

###
GET http://localhost:8080/swagger
Accept: application/json

###
GET http://localhost:8080/api-docs
Accept: application/json