springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger"
    operations-sorter: "method"
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 3000

spring:
  datasource:
    name: "HikariDataSource"
    username: "postgres"
    password: "admin"
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:postgresql://localhost:5432/ams"
    hikari:
      auto-commit: true
      connection-timeout: 300
      maximum-pool-size: 20

